<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-O1TFET3" failures="2" tests="2" name="Test(failed)" time="0.047" errors="0" timestamp="30 Apr 2023 08:41:36 GMT">
  <testcase classname="org.Day1.RerunTest" name="tc3" time="0.0">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at org.Day1.RerunTest.tc3(RerunTest.java:21)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- tc3 -->
  <testcase classname="org.Day1.RerunTest" name="tc2" time="0.0">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at org.Day1.RerunTest.tc2(RerunTest.java:9)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- tc2 -->
  <testcase classname="org.Day1.RerunTest" name="tc1" time="0.0">
    <ignored/>
  </testcase> <!-- tc1 -->
</testsuite> <!-- Test(failed) -->
